# Generated by Django 5.0.4 on 2024-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('breadName', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RB', 'Rabbits'), ('BD', 'Birds'), ('DG', 'Dogs'), ('CT', 'Cats'), ('HR', 'Horses'), ('FS', 'Fishes'), ('TR', 'Turtles'), ('SO', 'Seo Otter')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
